"use client";

import { FormEvent, useEffect, useState } from "react";
import { Heart, LoaderCircle, Music2, Send } from "lucide-react";
import { useParams } from "next/navigation";

type PublicItem={id:string;title:string;artist:string;votes:number};
export default function RequestPage(){const{venueId}=useParams<{venueId:string}>();const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);const[accepted,setAccepted]=useState<PublicItem[]>([]);
  async function refresh(){const response=await fetch(`/api/public/venues/${encodeURIComponent(venueId)}/requests`,{cache:"no-store"});const body=await response.json();setAccepted(body.data??[]);}
  useEffect(()=>{void refresh();const timer=window.setInterval(refresh,15000);return()=>window.clearInterval(timer);},[venueId]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage("");const form=event.currentTarget,body=Object.fromEntries(new FormData(form));const response=await fetch(`/api/public/venues/${encodeURIComponent(venueId)}/requests`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(response.ok){setMessage(result.data.votes>1?`Voto agregado. Ahora tiene ${result.data.votes} votos.`:"Solicitud enviada al DJ.");form.reset();}else setMessage(response.status===429?"Demasiadas solicitudes. Espera un minuto.":"No se pudo enviar la solicitud.");setLoading(false);}
  return <main className="min-h-screen bg-ink p-4"><section className="mx-auto max-w-md"><header className="py-8 text-center"><span className="mx-auto mb-3 grid h-14 w-14 place-items-center rounded-2xl bg-fuchsia-500/15 text-fuchsia-300"><Music2/></span><h1 className="text-2xl font-black">Pide tu canción</h1><p className="text-sm text-slate-500">Local: {venueId}</p></header><form onSubmit={submit} className="panel space-y-3 rounded-2xl p-5"><input name="title" required maxLength={180} placeholder="Nombre de la canción" className="w-full rounded-xl border border-slate-700 bg-ink px-4 py-3"/><input name="artist" required maxLength={180} placeholder="Artista" className="w-full rounded-xl border border-slate-700 bg-ink px-4 py-3"/><input name="requester" required maxLength={60} placeholder="Tu nombre o mesa" className="w-full rounded-xl border border-slate-700 bg-ink px-4 py-3"/><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-fuchsia-400 py-3 font-bold text-ink disabled:opacity-50">{loading?<LoaderCircle className="animate-spin" size={18}/>:<Send size={18}/>} Solicitar</button>{message&&<p className="rounded-lg bg-white/5 p-3 text-center text-sm text-slate-300">{message}</p>}</form><section className="mt-5"><h2 className="mb-2 text-sm font-bold text-slate-400">Próximas aceptadas</h2>{accepted.map(item=><div key={item.id} className="mb-2 flex items-center gap-3 rounded-xl border border-slate-800 p-3"><div className="min-w-0 flex-1"><b className="block truncate text-sm">{item.title}</b><small className="text-slate-500">{item.artist}</small></div><span className="flex items-center gap-1 text-xs text-fuchsia-300"><Heart size={13}/>{item.votes}</span></div>)}{!accepted.length&&<p className="py-5 text-center text-xs text-slate-600">El DJ aún no ha publicado próximas canciones.</p>}</section></section></main>;
}
